#!/bin/bash
docker run \
       --rm \
       -v "$(pwd):/usr/src/myapp" \
       -w /usr/src/myapp \
       golang:1.21.5 \
       go build -buildvcs=false -mod=readonly -o tofu-1.6.2 -ldflags="-s -w" -v

